### ISSUE TITLE
[feature_request] Sensoren über Stundenplan generieren

### ISSUE THREAD

**Issue by Kayhartmann** [rine77/homeassistantedupage#11]
Die Schule stellt keine Noten ( grades.py ) über edupage zur Verfügung und damit werden keine Sensoren erzeugt.

Die Lösung könnte sein, die Sensoren über den Stundenplan ( timetables.py ) abzurufen.

Oder die Möglichkeit Fächer manuel anzulegen

MfG

----

Translate by Google:

The school does not provide grades ( grades.py ) via edupage and therefore no sensors are created.

The solution could be to get the sensors via the timetable (timetables.py).

Or the option to create subjects manually

Kind regards

**Comment by rine77** [comment]
I dont get no answer to this issue since about 2 weeks.
https://github.com/EdupageAPI/edupage-api/issues/81
Tho I need it for this functionality.
Maybe I find time on weekend to dive in, fix and create pull request over there.

**Comment by Kayhartmann** [comment]
Hallo Rine77 ,
kannst du mir ein kleines tutorial verlinken wie ich die " test.py " mit und oder ohne Home Assistent debugen/Testen kann 

Translate by google:
---
Hello Rine77,
You can link me to a small tutorial on how I can debug/test the “test.py” with and or without the home assistant
