### ISSUE TITLE
How to use #2

### ISSUE THREAD

**Issue by brennyB** [rine77/homeassistantedupage#13]
ich würde diese Integration gerne nutzen.
Weis aber tatsächlich nicht wie.

Weder eine manuelle Installation war erfolgreich (mittels Copy & Paste) 
noch die per HACS  Repository. 

Installiere ich per Copy&Pase habe ich wenigstens Username und Passwort angeben 
bekomme eine Entity (Grades) welche aber keinen Inhalt hat. 

installiere ich per HACS kann ich lediglich die Version als Entity sehen.
(hier erschließt sich mir nicht wo ich die user / PWD und Subdomain hinterlegen kann)

generell vermute ich dass ich die EDUPAGE-API (github) benötige.
Wie ich diese aber installieren kann in meiner HomeAssistand VW-Ware erschließt sich mir nicht :-( 

ich wäre für jede Hilfe dankbar.

**Comment by brennyB** [comment]
Hallo Rine77,
danke für deine Rückmeldung.
d.h. ich muss nicht noch die EDUPage API installieren... das hat deine Integration schon im Bauch. 
die HACS integration habe ich dank deinem Hinweis (Punkte 11- 13) nun auch hinbekommen.

Noten sind leider bei und leider noch keine hinterlegt.,..
Bekomme aber auch keine weiteren Fehlermeldungen, fühlt sich also so an als würde der Login klappen...

bin gespannt wie es mit Deiner integration weitergeht...
hoffe ja dass ich für jedes meiner Kinder früher oder später ein Dashboard erstellen kann mit 
-> Stundenplan
-> Vertretungsinformationen
- > aktuellen Hausaufgaben
- Klassenbucheinträgen ;-)
-  anstehenden Klassenarbeiten....
Hallo Rine77,
danke für deine Rückmeldung.
d.h. ich muss nicht noch die EDUPage API installieren... das hat deine Integration schon im Bauch. 
die HACS integration habe ich dank deinem Hinweis (Punkte 11- 13) nun auch hinbekommen.

Noten sind leider bei und leider noch keine hinterlegt.,..
Bekomme aber auch keine weiteren Fehlermeldungen, fühlt sich also so an als würde der Login klappen...

bin gespannt wie es mit Deiner integration weitergeht...
hoffe ja dass ich für jedes meiner Kinder früher oder später ein Dashboard erstellen kann mit 
-> Stundenplan
-> Vertretungsinformationen
- > aktuellen Hausaufgaben
- Klassenbucheinträgen ;-)
-  anstehenden Klassenarbeiten....


Gruß und danke für die Unterstützung

**Comment by rine77** [comment]
Danke für dein Feedback. Weil ihr hier so mitmacht mache ich überhaupt weiter. Ich brauchte eigentlich nur die Noten. Du kannst gern helfen, indem du beim Testen hilfst und Feedback gibst.

Ich schaue mir als nächstes Stundenplan und Hausaufgaben an. Beides sollen Einträge in einem Homeassistant Kalender werden.

Gruß aus Thüringen

**Comment by rine77** [comment]
Ich habe die Stundenpläne jetzt in dieser Art integriert. Man kann nun mehrere Kinder auswählen und jedes erhält dann unabhängig voneinander Kalender, Noten usw.
Wird dir das helfen?

![image](https://github.com/user-attachments/assets/df34a98c-917b-4af9-9e77-266cee03916c)

**Comment by Nefesar** [comment]
Sieht gut aus 👍🏻

**Comment by brennyB** [comment]
Grade noch mal bissl rumgetestet... 
Lösche ich Kind 1 bekomme ich Entitäten für Kind 2 :-)

**Comment by rine77** [comment]
aktuell in der Version gibt es nur die Möglichkeit, für 1 Kind die Sensoren der Schulfächer mit Noten, wenn vorhanden, anzulegen.
Im nächsten Release ist es möglich, beliebig viele Kinder mit einzelnen Sensoren und den Stundenplänen als Home Assistant Kalender anzulegen. 

Ich hoffe, dass das morgen fertig ist. Die Funktionalität ist vorhanden - aber es gibt noch ein oder zwei entscheidende Bugs. Die Sensor-Plattform und die Calendar-Plattform behindern sich noch gegenseitig, einzeln funktioniert schon alles. 

Also einfach noch kurz abwarten, das wird bald kommen  :)

Danke für euer Feedback!

**Comment by rine77** [comment]
ok habs doch heute noch gemacht. Gern testen.

**Comment by brennyB** [comment]
Moin, Sorry habe es gestern abend nicht mehr geschafft zu testen.
Heute morgen aber dafür :-) 

2 Kinder getestet...
Stundenpläne sind jetzt im Kalender integriert :-)

sehr schön! danke! 
freue mich auf die kommenden Features
