### ISSUE TITLE
[feature_request] Grades are not loaded with max points

### ISSUE THREAD

**Issue by mgrfilipmarek** [rine77/homeassistantedupage#14]
**Describe the bug**
In our school, kids are evaluated with points. In HA, only achieved points are loaded but no max. But in Edupage, I can see achieved/max value.

**Comment by rine77** [comment]
can you deliver a screenshot?

**Comment by mgrfilipmarek** [comment]
HA:
![image](https://github.com/user-attachments/assets/ed4835ce-24d8-479a-8993-f5137ea8236a)
Edupage:
![image](https://github.com/user-attachments/assets/137f2e07-1e10-4665-bd17-6ab2e438e69a)

**Comment by rine77** [comment]
Ok I think I got it now. I try to find out if supported by API.
