### ISSUE TITLE
[bug] Use english in names, variables, IDs

### ISSUE THREAD

**Issue by mgrfilipmarek** [rine77/homeassistantedupage#15]
**Describe the bug**
This one is not really a bug. But I think that for the future of this integration it would be perfect to use English. (As its standard for all developers).
For example:
![image](https://github.com/user-attachments/assets/37c8f4b2-cf99-4ad7-a9d3-b7288bccfd75)

**Comment by rine77** [comment]
I fixed it as far as I can see. If you find more, please notify me, thanks
