### ISSUE TITLE
Subject unavailable

### ISSUE THREAD

**Issue by mgrfilipmarek** [rine77/homeassistantedupage#21]
**Describe the bug**
One of my entities/sensors for grades is not available.

**Screenshots**
![image](https://github.com/user-attachments/assets/889aa929-d412-4d3d-9664-0c2a31e7af84)

**Comment by rine77** [comment]
what version? Did you update today?

**Comment by mgrfilipmarek** [comment]
It was there in prev. version. After I updated today and re-imported integration its not working properly.

**Comment by rine77** [comment]
When I updated in my production HA I had to delete the old sensors manually, than reinstalled integration and all is fine. Could you try this please?

**Comment by mgrfilipmarek** [comment]
Still a bit weird.
![image](https://github.com/user-attachments/assets/f7595e7f-4c83-4a61-84d7-34d11a7e328b)

**Comment by rine77** [comment]
okay step-by-step:
1. how many sensor should be there?
2. how many are there?
3. what are characteristics of the failing sensor(s)?
4. do you have access to the logs (somewhere under "system" or something in Home Assistant)

**Comment by mgrfilipmarek** [comment]
I found this in logs: 
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:918
integration: Sensor (documentation, issues)
First occurred: 3:22:39 PM (1 occurrences)
Last logged: 3:22:39 PM

Error adding entity sensor.edupage_subject_vytvarna_vychova for domain sensor with platform homeassistantedupage
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1368, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1073, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homeassistantedupage/sensor.py", line 70, in extra_state_attributes
    attributes[f"grade_{i+1}_teacher"] = grade.teacher.name
                                         ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by rine77** [comment]
OK looks like the problem is there are is no teacher-name. My codes doesnt check if there alway a teacher. When it accesses the Attribute it fails, cause there is nothing.

I will add a branch and try to fix this, gimme some minutes.

**Comment by mgrfilipmarek** [comment]
you can just include in next release :) No hurry....
Btw. version is not matching I guess:
![image](https://github.com/user-attachments/assets/444a8602-9154-4ba5-9dc2-e69337cf63cd)

**Comment by rine77** [comment]
maybe you could try 0.1.4 (also fixed version missmatch)

**Comment by mgrfilipmarek** [comment]
works fine :)
