### ISSUE TITLE
[bug] Not unique ID

### ISSUE THREAD

**Issue by mgrfilipmarek** [rine77/homeassistantedupage#25]
**Describe the bug**
There is an error in my log but I did not noticed any issues so far.

**Logs**
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:764
integration: Sensor (documentation, issues)
First occurred: November 22, 2024 at 4:07:34 PM (1 occurrences)
Last logged: November 22, 2024 at 4:07:34 PM

Platform homeassistantedupage does not generate unique IDs. ID edupage_grades_náboženská_výchova already exists - ignoring sensor.edupage_subject_nabozenska_vychova

**Comment by rine77** [comment]
this is being fixed with the next release. Every sensor will geht a unique_id.

**Comment by rine77** [comment]
please test if unique_id is fine.
