### ISSUE TITLE
[bug] timetables not loading

### ISSUE THREAD

**Issue by Nefesar** [rine77/homeassistantedupage#30]
Bei mir hat alles soweit geklappt bei den Kalender können keine Termine geladen werden jedenfalls bei mir.

**Comment by rine77** [comment]
1.  Frage: Gibt es denn den Stundenplan wenn du dich einloggst per Browser?
  2.  Frage: es werden Stunden 14 Tage im Voraus geladen - hast du mal vorgeblättert?
  3.  Ein Screenshot wäre nice :)

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Nefesar ***@***.***>
Gesendet: Sunday, November 24, 2024 9:57:18 PM
An: rine77/homeassistantedupage ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [rine77/homeassistantedupage] Termine könnten nicht geladen werden (Issue #30)


Bei mir hat alles soweit geklappt bei den Kalender können keine Termine geladen werden jedenfalls bei mir.

**Comment by Nefesar** [comment]
Ja der Stundenplan kann man einsehen jetzt schon bis Ende des Jahres er wird mir auch in Browser angezeigt.Habe vor der neuen Version alles entfernt Neustart gemacht und wie gewohnt wieder über Hacs installiert.Mfg Sven --Gesendet mit der GMX Mail AppAm 24.11.24, 22:17 schrieb rine77 ***@***.***>:

  1.  Frage: Gibt es denn den Stundenplan wenn du dich einloggst per Browser?

  2.  Frage: es werden Stunden 14 Tage im Voraus geladen - hast du mal vorgeblättert?

  3.  Ein Screenshot wäre nice :)



Gesendet von Outlook für iOS<https://aka.ms/o0ukef>

________________________________

Von: Nefesar ***@***.***>

Gesendet: Sunday, November 24, 2024 9:57:18 PM

An: rine77/homeassistantedupage ***@***.***>

Cc: Subscribed ***@***.***>

Betreff: [rine77/homeassistantedupage] Termine könnten nicht geladen werden (Issue #30)





Bei mir hat alles soweit geklappt bei den Kalender können keine Termine geladen werden jedenfalls bei mir.

**Comment by Nefesar** [comment]
Die Fehlermeldung im Log:Fehlermeldung 1.Dieser Fehler stammt von einer benutzerdefinierten IntegrationLogger: custom_components.homeassistantedupage.homeassistant_edupageQuelle: custom_components/homeassistantedupage/homeassistant_edupage.py:40Integration: homeassistantedupage (Dokumentation, Probleme)Erstmals aufgetreten: 08:42:42 (2 Vorkommnisse)Zuletzt protokolliert: 08:42:44EDUPAGE unexpected login error: list index out of rangeFehlermeldung 2.Logger: homeassistant.components.sensorQuelle: helpers/entity_platform.py:764Integration: Sensor (Dokumentation, Probleme)Erstmals aufgetreten: 08:41:30 (13 Vorkommnisse)Zuletzt protokolliert: 08:42:44Platform mqtt does not generate unique IDs. ID Generated_Day already exists - ignoring sensor.hm800_generated_dayPlatform mqtt does not generate unique IDs. ID Generated_All already exists - ignoring sensor.hm800_generated_allPlatform mqtt does not generate unique IDs. ID BatterySOC already exists - ignoring sensor.hm800_batterysocPlatform mqtt does not generate unique IDs. ID Consumed_Day already exists - ignoring sensor.hm800_consumed_dayPlatform homeassistantedupage does not generate unique IDs. ID edupage_grades_-18_kunst already exists - ignoring sensor.alvin_nothnagel_kunst--Gesendet mit der GMX Mail AppAm 24.11.24, 22:17 schrieb rine77 ***@***.***>:

  1.  Frage: Gibt es denn den Stundenplan wenn du dich einloggst per Browser?

  2.  Frage: es werden Stunden 14 Tage im Voraus geladen - hast du mal vorgeblättert?

  3.  Ein Screenshot wäre nice :)



Gesendet von Outlook für iOS<https://aka.ms/o0ukef>

________________________________

Von: Nefesar ***@***.***>

Gesendet: Sunday, November 24, 2024 9:57:18 PM

An: rine77/homeassistantedupage ***@***.***>

Cc: Subscribed ***@***.***>

Betreff: [rine77/homeassistantedupage] Termine könnten nicht geladen werden (Issue #30)





Bei mir hat alles soweit geklappt bei den Kalender können keine Termine geladen werden jedenfalls bei mir.

**Comment by Nefesar** [comment]
Fehler zwei hat nichts edupage zu tun sorry --Gesendet mit der GMX Mail AppAm 25.11.24, 08:53 schrieb Sven Nothnagel ***@***.***>:
Die Fehlermeldung im Log:Fehlermeldung 1.Dieser Fehler stammt von einer benutzerdefinierten IntegrationLogger: custom_components.homeassistantedupage.homeassistant_edupageQuelle: custom_components/homeassistantedupage/homeassistant_edupage.py:40Integration: homeassistantedupage (Dokumentation, Probleme)Erstmals aufgetreten: 08:42:42 (2 Vorkommnisse)Zuletzt protokolliert: 08:42:44EDUPAGE unexpected login error: list index out of rangeFehlermeldung 2.Logger: homeassistant.components.sensorQuelle: helpers/entity_platform.py:764Integration: Sensor (Dokumentation, Probleme)Erstmals aufgetreten: 08:41:30 (13 Vorkommnisse)Zuletzt protokolliert: 08:42:44Platform mqtt does not generate unique IDs. ID Generated_Day already exists - ignoring sensor.hm800_generated_dayPlatform mqtt does not generate unique IDs. ID Generated_All already exists - ignoring sensor.hm800_generated_allPlatform mqtt does not generate unique IDs. ID BatterySOC already exists - ignoring sensor.hm800_batterysocPlatform mqtt does not generate unique IDs. ID Consumed_Day already exists - ignoring sensor.hm800_consumed_dayPlatform homeassistantedupage does not generate unique IDs. ID edupage_grades_-18_kunst already exists - ignoring sensor.alvin_nothnagel_kunst--Gesendet mit der GMX Mail AppAm 24.11.24, 22:17 schrieb rine77 ***@***.***>:

  1.  Frage: Gibt es denn den Stundenplan wenn du dich einloggst per Browser?

  2.  Frage: es werden Stunden 14 Tage im Voraus geladen - hast du mal vorgeblättert?

  3.  Ein Screenshot wäre nice :)



Gesendet von Outlook für iOS<https://aka.ms/o0ukef>

________________________________

Von: Nefesar ***@***.***>

Gesendet: Sunday, November 24, 2024 9:57:18 PM

An: rine77/homeassistantedupage ***@***.***>

Cc: Subscribed ***@***.***>

Betreff: [rine77/homeassistantedupage] Termine könnten nicht geladen werden (Issue #30)





Bei mir hat alles soweit geklappt bei den Kalender können keine Termine geladen werden jedenfalls bei mir.

**Comment by rine77** [comment]
Die Fehlermeldungen sind "okay", sollten also nicht das Laden der Stundenpläne verhindern.

**Comment by rine77** [comment]
bitte mit der neuen Version probieren und im Notfall neu aufmachen.

Please try with the new version, and if necessary, reopen the issue.
