### ISSUE TITLE
[feature request] respect lesson is_cancelled attribute

### ISSUE THREAD

**Issue by bbirnbach** [rine77/homeassistantedupage#52]
**Is your feature request related to a problem? Please describe.**
Canceled lessons are still visible in calendar. They have a is_cancelled attribute which needs to be evaluated.

**Describe the solution you'd like**
Question: How to handle canceled Events? 

1.  delete them
2. mark them as canceled -> i don't think HA can display canceled events
    2.1. maybe a prefix like "(canceled)" or something?!

Any suggestions are welcome.

**Comment by rine77** [comment]
"cancelled" as event title prefix should be the best solution.

**Comment by bbirnbach** [comment]
> "cancelled" as event title prefix should be the best solution.

I just did it like this. PR can be marked as ready if you think its fine.
