### ISSUE TITLE
[feature_request] School timetable

### ISSUE THREAD

**Issue by mgrfilipmarek** [rine77/homeassistantedupage#8]
**Describe the solution you'd like**
It wold be nice to view timetable for current year via HA.

**Describe alternatives you've considered**
It should be considered how addon will behave if siblings are within one edupage account (school).

**Comment by rine77** [comment]
I dont know if it is possible to get the whole year, its a lot of data and I bet it's based on semesters or something.
But to have a weekwise or monthwise calendar in HA could be a nice thing.

**Comment by rine77** [comment]
maybe this is what you have in mind
[https://github.com/rine77/homeassistantedupage/discussions/26](https://github.com/rine77/homeassistantedupage/discussions/26)
