### ISSUE TITLE
[feature_request] Load messages and notifications

### ISSUE THREAD

**Issue by mgrfilipmarek** [rine77/homeassistantedupage#9]
**Describe the solution you'd like**
I would like to read all messages and notifications from teachers in HA directly.

**Comment by rine77** [comment]
there is a get_notifications() functions, so it's possible.
What type of sensor should this be in Home Assistant?

**Comment by mgrfilipmarek** [comment]
Hmm, hard to say what would be the best. But probably as calendar entity.
